<?php
define("INDIAN_STATES", [ 
    "Andhra Pradesh" => "Andhra Pradesh",
    "Arunachal Pradesh" => "Arunachal Pradesh",
    "Assam" => "Assam",
    "Bihar" => "Bihar",
    "Chandigarh (UT)" => "Chandigarh (UT)",
    "Chhattisgarh" => "Chhattisgarh",
    "Delhi (NCT)" => "Delhi (NCT)",
    "Goa" => "Goa",
    "Gujarat" => "Gujarat",
    "Haryana" => "Haryana",
    "Himachal Pradesh" => "Himachal Pradesh",
    "Jammu and Kashmir" => "Jammu and Kashmir",
    "Jharkhand" => "Jharkhand",
    "Karnataka" => "Karnataka",
    "Kerala" => "Kerala",
    "Lakshadweep (UT)" => "Lakshadweep (UT)",
    "Madhya Pradesh" => "Madhya Pradesh",
    "Maharashtra" => "Maharashtra",
    "Manipur" => "Manipur",
    "Meghalaya" => "Meghalaya",
    "Mizoram" => "Mizoram",
    "Nagaland" => "Nagaland",
    "Odisha" => "Odisha",
    "Puducherry (UT)" => "Puducherry (UT)",
    "Punjab" => "Punjab",
    "Rajasthan" => "Rajasthan",
    "Sikkim" => "Sikkim",
    "Tamil Nadu" => "Tamil Nadu",
    "Telangana" => "Telangana",
    "Tripura" => "Tripura",
    "Uttarakhand" => "Uttarakhand",
    "Uttar Pradesh" => "Uttar Pradesh",
    "West Bengal" => "West Bengal"
]);
?>
